# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CometChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CometChat
  pod 'CometChatPro', '~> 1.8.8'
  pod 'Kingfisher', '~> 5.0'
end
